### ISSUE TITLE
Declare source of validation in docs

### ISSUE THREAD

**Issue by jaromil** [aral/isvat#1]
Finding this code (and the commercial service related to it) immediately raised a doubt in me: what is the source of this validation, is it the official VIES database provided by the EU commission?

I have found no answer to this nor in the documentation of the code or in the commercial service. Had to look in the code to find that yes, in `isvat/isvat/api/views.py` at line 16 it seems this all boils down to a x-form query to the CGI provided by VIES.

I believe it helps anyone looking at this software to know that this is a rather sophisticated wrapper to VIES, perhaps mentioning it in the software documentation (README), rather than in a template page that appears only after installing the whole software.

Also this discovery still leaves me a curiosity about the software: is it caching responses? Or in any case what are the advantages in using this code rather than calling directly the VIES CGI?

**Comment by aral** [comment]
Hey @jaromil,

I am not involved in maintaining this code — it was a quick hack a few years ago to scratch my own itch. The vatlayer folks are running the paid service (I’m not sure if they’re actually using the code here or if they’ve rewritten it).

**Comment by jaromil** [comment]
ACK. Thanks, good to know. I anyway doubt there is a different source than VIES for this validation, since these are likely randomly assigned numbers.
